openapi: 3.0.1
info:
  title: Network-API
  version: 0.0.1-SNAPSHOT
servers:
- url: /api/v1/
paths:
  /users/{userId}:
    get:
      description: Get user info
      operationId: getUser
      parameters:
      - description: Id of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: Get user infos
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /users/:
    post:
      description: Create a new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        description: Create user input
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /activity/{activityId}:
    get:
      description: Get activity info
      operationId: getActivity
      parameters:
      - description: Id of the activity
        explode: false
        in: path
        name: activityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: Get activity info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
  /activity/:
    post:
      description: Create a new activity
      operationId: createActivity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityRequest'
        description: Create activity
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
components:
  schemas:
    CreateUserRequest:
      additionalProperties: false
      example:
        name: Olivier
      properties:
        name:
          type: string
      required:
      - name
      type: object
    GetUserResponse:
      additionalProperties: false
      example:
        name: name
        userId: userId
      properties:
        userId:
          type: string
        name:
          type: string
      required:
      - name
      - userId
      type: object
    CreateActivityRequest:
      additionalProperties: false
      example:
        name: Cooking
      properties:
        name:
          type: string
      required:
      - name
      type: object
    GetActivityResponse:
      additionalProperties: false
      example:
        activityId: activityId
        name: name
      properties:
        activityId:
          type: string
        name:
          type: string
      required:
      - activityId
      - name
      type: object
    ErrorResponse:
      additionalProperties: true
      type: object
