openapi: 3.0.1

info:
  title: Network-API
  version: 0.0.1-SNAPSHOT

servers:
  - url: /api/v1/

paths:
  /users/{userId}:
    get:
      description: Get user info
      operationId: getUser
      parameters:
        - name: userId
          description: Id of the user
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: Get user infos
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User
  /users/:
    post:
      description: Create a new user
      operationId: createUser
      requestBody:
        description: Create user input
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User

    get:
      description: Get user list
      operationId: getUsers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
          description: User list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User

  /activity/{activityId}:
    get:
      description: Get activity info
      operationId: getActivity
      parameters:
        - name: activityId
          description: Id of the activity
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: Get activity info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity
  /activity/:
    post:
      description: Create a new activity
      operationId: createActivity
      requestBody:
        description: Create activity
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity
    get:
      description: Get activity list
      operationId: getActivities
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
          description: Activity list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity

components:
  schemas:
    CreateUserRequest:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: Olivier

    GetUserResponse:
      type: object
      additionalProperties: false
      required:
        - userId
        - name
      properties:
        userId:
          type: string
        name:
          type: string

    GetUsersResponse:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/GetUserResponse'
      example:
        - name: Guillaume
          userId: 467366a1-af34-468a-9363-480699272ee0
        - name: Olivier
          userId: 467366a1-af34-468a-9363-480699272ee1


    CreateActivityRequest:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: Cooking

    GetActivityResponse:
      type: object
      additionalProperties: false
      required:
        - activityId
        - name
      properties:
        activityId:
          type: string
        name:
          type: string

    GetActivitiesResponse:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/GetActivityResponse'
      example:
        - name: Cooking
          activityId: 467366a1-af34-468a-9363-480699272ee0
        - name: Tennis
          activityId: 467366a1-af34-468a-9363-480699272ee1


    ErrorResponse:
      type: object
      additionalProperties: true


