openapi: 3.0.1

info:
  title: Network-API
  version: 0.0.1-SNAPSHOT

servers:
  - url: /api/v1/

paths:
  /users/{userId}:
    get:
      description: Get user info
      operationId: getUser
      parameters:
        - name: userId
          description: Id of the user
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User's project list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User
  /users/:
    post:
      description: Create a new user
      operationId: createUser
      requestBody:
        description: Create user input
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User

components:
  schemas:
    Date:
      title: Date in JSON format
      type: string
      example: 2021-07-28T14:37:09.234Z

    NullableEmptyObject:
      title: Nullable empty object
      type: object
      additionalProperties: false
      nullable: true

    CreateUserRequest:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: John

    GetUserResponse:
      type: object
      additionalProperties: false
      required:
        - userId
        - name
      properties:
        userId:
          type: string
        name:
          type: string

    ErrorResponse:
      type: object
      additionalProperties: true


